#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  27/8/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

explorer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAO9J"
    "REFUOI1jYGRiZhA3iv2//dKT/zCakYmZgVjMwsDAwDAp+BqDq440w9MzixjWtpswMDAwMNRM"
    "3vmfAQ38/fOH4ffvvwx/fv9mYGBgYPjz+w/EAGygJdedEZccMmBhYGBgePKJjeEvVODJJzZi"
    "9KEa8PEXC0NrsR2yEPEAOUCyG1aiBCAxgcuEz3DkwP202R+3F5BBVt0ypNDvwtBQ0rXpP95Y"
    "mNYUBQ99pVKz/+iB21PmhxI7eEOMmMDFa0DzxGME0wLeQBQziPq/7cLD/zCaZAPoEgt4c1pv"
    "ueX/n//+///57///3nJLrAmJ4lgAACWjf/lf+gFyAAAAAElFTkSuQmCC"
    )
