#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  1/9/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

# ----------------------------------------------------------------------
smiles = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAolJ"
    "REFUOI1tk91Lk2EYxn/vx7OmwyBhVsytmY1cCBFBQWSRlYVGJ51EjajptliH4X/QQeJ5J+ZJ"
    "f0AnIVSWJ0EQQfQhzNG3JkRQILrl3tft6sDNRvnAdfI8z8V939d13Vi2w79IpS4pHt8p17Vk"
    "jK1EIqpcLqPN/to0nWwmrc5IUL29n3jw4Ajl8mVKpYvcv7+frq5HdEZqymauqZljWbYDwOlT"
    "xxSL/eTOnfMY4wElYAWoAhXgI75fIJ/3mJ8/wvST5xaw3kE2k1YsBhMTtzEmCYTqxEaxVaCM"
    "MRYTE1uIxZ6RzVxdf7Rsh2i0XZ5XkPRF0mONjo4KkJSSlBKgcDgsqVVSizwPRTuRZTu42Uxa"
    "XV1rGNMCOECN8fHxpimX6OnpYW5uDmgF1TAEuXG9yuf5lOyZmYcMDUWAReAj8LqJXAEWWVhY"
    "aLqrQaWVoZNtzMxMYRljq1S6iTFtwCrDw9+ZnPQ2hIOFuqB1crUKSx34qw6hXfMNG7264stM"
    "TvrAEvAOKDaRBVpjd2cQ/BbwgwDY8XiEYvEb8AMokky+BF7UK+svGR+qNp+/L0O5jeKcRXxX"
    "GLe//wxTU/fo7Q0AolCAUEiUGoWpAWtQtTi4rw19iUB5K1OPf9F//GTDRkue11K3ad0qBYMK"
    "BAJyXUehoKv93e3S4l6p0Cfv1QlFdwS0EeXBwTT5/Op6mw389qn4Pr5jcTjZweunUVgOw1qA"
    "/K0ig2fOsREky3YYGOjTyAjyPCTVUbWllW3St6T04ZC8N0c1cmGHBo4f0H/LNP3kueU4w3R3"
    "w9gYzM6CX3HwKzaz71cYu/uV7rMvcLb2Mf3srbURi81WNJdLK5HYLuMi46LEng7lMlc2Xec/"
    "xiMt8QU2mDwAAAAASUVORK5CYII=")

# ----------------------------------------------------------------------
small_up_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUOI1jZGRiZqAEMFGke2gY8P/f3/9kGwDTjM8QnAaga8JlCG3CAJdt2MQxDCAUaOjyjKMp"
    "cRAYAABS2CPsss3BWQAAAABJRU5ErkJggg==")

# ----------------------------------------------------------------------
small_dn_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEhJ"
    "REFUOI1jZGRiZqAEMFGke9QABgYGBgYWdIH///7+J6SJkYmZEacLkCUJacZqAD5DsInTLhDR"
    "bcPlKrwugGnCFy6Mo3mBAQChDgRlP4RC7wAAAABJRU5ErkJggg==")

run_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAPhJ"
    "REFUOI1jYBgFjNgEsxebf/315xfXr39/uBYmX/6OzwAmbII//vxikBHRZPjx+/c3/6nynCQb"
    "wMPGw6UpYc4gK6zO8O3Xjy+23YI8JBnw598vhmcfHzPoylgzKIvpM/348+2jbjMjP0le+Pb3"
    "O8PDd3cZDGRtGdQlTZl+/Pn/lgQDfjD8//ufQZRXmuHc46MMR+8eef3tF4MJNrUs2AS//fnB"
    "IMgtxnD64RGGvbd2vfj1h8H5eTvDNWxqmbEKWnws+/+fmXX/zT1Pf/1lcHreznADmzoGBhzp"
    "QLGW4evff8xc3//9VXrdznAfl2a8QLicAW/8Dx4AAHR1YeN2C0QUAAAAAElFTkSuQmCC")

refresh_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALNJ"
    "REFUOI2lk7ENwyAQRR/EUopUtBRRRrHEAh7E43gQFkDyKFEKt65SkyZEGLBNxK/Qcf/r7t+d"
    "8N57GiBbyABdGtBjnyUt01wnoMceMygAnF0zYhCP4zL+PCObQWEGtamyyoNYHNiInAqERGfX"
    "Xyy89djnJqYIraTmhnhXcj0mHE0AQIaEtMcaMnw9WKYZZ1eu8gKUp7AHEa/yXtlHIxalW3i9"
    "n9xvj6qtLAr8g+Zjahb4AEW6VPXp5dKQAAAAAElFTkSuQmCC")

# ---------------------------------------------------------------------

change_normalization = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtlJ"
    "REFUOI2l011sTGkYB/D/OfPRj6O0THVMfU5bSTWpcGy0vhMyNljJSnAhrgQJLsTFJnvBnbjD"
    "BRd1sSEp2WR9hERtNruEIrpyhLFV206nVUa100Or8/E+z3vmvC7oNNSNeG7/ye/JP08eTcP3"
    "jRcAVv820ATA/EpuATgGwAcgpZSy7+wK8gQgl8u1QilzeyRkEqmPgUfDxZuv8fOaGXPsES5P"
    "DAnue5NNrTiT6Li7p7J/DNAB4O7uULPjOH+eb+mzNOUiPSpBlIPjOJDsaobPU1ETLJ6zsbG8"
    "zu9VkYbTveHPAPNEZwg5uXzT0unm0GAGhQWAFBKSGX/83TPa1j5QkspS9bAtqiJLAos05LaZ"
    "JzpL84DDvGVusLB65F0GXq/ChZYuy+cHHCJYB2usvsTIXzdaX2QFc9geTFfPDhTUO8wr8wAT"
    "LZ9meKcySfzbPtDNRA/OXnlmMREA4PEvdY8k851obKiISYYDJd5aJlqdB6QQNR4dxY5y0d2T"
    "HO44Yh5wiE46RNZY12eHF7fEe5J+R7mVHh1hKcQP+SswUTrrqPfSUWCiNAB0HV3WDKB51qF/"
    "mgC0vjy+tpmJjLSjJvugwETGeAUhHiZHKW4LN1EeMDi47/qGsc2SyJREB4P7W06VB4xSW7hI"
    "pijDQnSNVyC63fdqqMOGL142rzIrmVdN3XV58acMa7csMyVRQ2BBVZUNH14m7LeS6N44wNza"
    "+/+LaGGpEUt4jHh4XUNRSUVZpGTn7yYToTujY+HWdWYsq8M1ihFr741J5ssA4NEA0JOLQpv/"
    "0+uBzl5/xZK6TL8qeIuZs6isvnZk+FE0UrSoPhRPa5hR6sfTc5esnJS30hd2XM0DACD/u/LO"
    "nffjYDL6XPlYZPWiAqGmTE4Pt1nryxrNkPJ6kFI65jbWh/rvW4ZeuznjPr8W1b78Rn1zk18p"
    "NQ3AJE3TJIBflVITHk3TNMu9tnfvBOBb5wOI/oIVnOBIyAAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------

selected_data = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAIUAAAAXCAYAAAAldIx0AAAABHNCSVQICAgIfAhkiAAADWhJ"
    "REFUaIHtmntwVNUdxz93s3k/gARIAgg2RCgQeQg0kecSlJeKAaoDikLHF5FHAa1KBdpGO4AB"
    "im2Z1ipFQQUEFUaIkdi6gEhJVawKtchDhYRoEh4JJNlNdk//uI899+69m9DOdKYznpmdvXvO"
    "7/H9/c7vcc5NFMUVxffj+yEPd1uI7rkrIBITQVFA0eYEoWd56PNC+61YaO3mrXNIv+1kWtes"
    "ww6jFW9r+GhlvbXfkfjtbGnNR23B7cQP4FIgMRHS0uDxJ6Psti6Ex6lSjB0dEJkZ0Csb+vaB"
    "1A4QFYW9F5x2WEYozzkNu0iLtOtXIyNSBNvRWO2wo9fXW4tqJ5l2Oq4Wt9OcjW2KAj4/XLgI"
    "wRbIzITRE8IDxDYoxo4MiIH9YXguZGdB544QH9c2m+xiRJEWWttjp0ri6G9JrlNm2dE66Zcx"
    "GOtCm1MiVzjHnLDZREWAUOx92ZZqYh1OMS3zAgRaoK4eLtSBrwliomFwvjkwwoIif3hADB0E"
    "N4+GH2ZDSjK43WqURcx+O0vsLHJC6zQiecGOpjX5kfrOfzuc7IxE6zTXmi+ddEbQLbT5QABa"
    "AmrFOH9RbS033BwKDFNQ5A8LiCED4KaRkNMLkpLUlhGWaUKbU0LTRonSMsDAa0OrCJM4U6ab"
    "5nVZQgtKy7rQ5g2Zdjp0TJIPjWohJF8qZrkS5JCPFWldWjT2QbHh0zFKPIpkl0mO5FtDnk3w"
    "y7bZkgkzvyIRCAUIqmstLXD+EtRfhrhY6DVKDQwjKMbkBcTAvjBhNPS7DpKTIMolaYpUuyIN"
    "p3ouILGflyvHPG3n/S9GYt9WdP0Px3+Exak/OtG1Jk6vGkFoblafE+IhsV+UYtw+MtIg73ro"
    "3Q0SY8DVbASUOVOsWWfBA87Y7aqb8EkRb6kgcjYplqyy2q9XhKRBXi4f8YTp1HWZ8MiZK2OX"
    "K4KNHVZb7YYpU2V9OnY/JkfYdg3tR7JkU6RuGPas8Ydh0Z6DAtwuiI/VpgIqvxEU2V0hKxMS"
    "okHxQVA7Q1hByGXQWkZN84ScLltsPXgFfRJ4S4tw0isTyDp0HkOmxFt32GPSpeMx6ZIwCOuG"
    "OfRuGbMTeGGjM9hk4YkkD7OfZJ8Li50mOTaRa4ImIKCAK6i2Dz0aXADTxwVE7+7QKRFcLUAz"
    "BP0qkKBPzbCg9Ll0IZ6l6x5iwLSX6TyylK5jdjN57mpK3stT6f0q//7D/Rk96w90HLmXfrdv"
    "5aXXJxnretYKTY/ww4HD/fHM+gMdR+yl32SJvkmVJ3zw1dedeXD5E2RPep20EXu5ccYL7CgZ"
    "Q9APKXleQP1OyVU/QpNtPPvU9ZZGhVV/mkm/yVtJG76XgdM288ctBQSbMHiEHz49lsXkecWk"
    "j3qbHuN2seDXi7hcF0tKrtfwjfwJSrxHv7iWKQtWGbwLVyziyqVYdZP9IT+crUjjkZULyBxT"
    "Qs7tW1i67iEa6qJVrLkWm/K8IZ/4oOJsGotXLiDTU0JOgcrbWB+t7pW2D6IpHKfu00ATBBu1"
    "gEiE4PGAcAEkxECHOIgBFH8oEHTQ8kYKP8x5agnNvih2rlrMN7tu4R+bZ/BQwQ6e2z7VoD9+"
    "shv3Li3i4Snb+XJHARuX/pLiTTM5UD7ACC49A4QP/nWiG/csLaJwyna+3G6hb1Zpvj7TmXGF"
    "67k2vZK96+ZyZtck1v50LTvK8hE+uFDmAdRv/WPS5Q89LypeRGNDLDtXLeb0G7fx7MJi1m+7"
    "g9f3jjF4jp/sRsHi1UzKO8gnm2fwtxdm0eea0yxY+agpoI2P5K+TpzOZvHAtYweXc2TTXRx6"
    "fjY9M88wb8XPVF6JZ3zhegZkHeeLbVN5q3gh31Sms3LDbIJ+uPBuuE3CFwqqcYXrGWjhXbFh"
    "tjlQrTglrDRrrSyoVQ+3dtC8b1JATPPAgJ4QF2OpUDan3+7TSvh8049JSWgIzVtuCHPWLCHn"
    "ByeZN/U1Q17JoWG8VHob2361BASk3uqldo8HBZizegk5WSeZO+U145S/59AwNpXextZfLkEB"
    "5q57nIzUGpbN2mDu9/qpXYHUW7yc3+MJO+2n3hqaT7vVy6PTX2LJzI3qutbWyspzKd4yi7K1"
    "DyOAB4ufpO+1p1h4xxZDmSKgeOtMVrx8P+d3e0wtU75lzCn+OT27nuGxGZuN2w3Ais2zKd46"
    "m9o9nrAer7fXi/VJ5C98jo833I2CalPtHo+mCPMtSJetzV/QeI9suDtED+bbjtRWFAHR0ZCU"
    "DiQBLVr7UIJatGjlxIhiSynVI69Xt69Y/qdCKs+lqfNN4VlTfjSH8YMOmtpPXq9P+exUthGp"
    "csaUH8th/MCDpup043UqvS77rx8OZfqoUlMl07NA+EN92lTZbKoSwPRRpeZK6IMhPY9yoqKb"
    "kUX7PxlMQd57Ifu1kjtt2F9UeX7JT36zXu+RIfx42LshbBrdnaPeMewWPmioj2bV5nv50YOb"
    "6DKllLRbvPScvpsz32WYsAvJZn2+8XI0z7x8Lz96YBNdppaSKvHq+owW4sO0V4Ycbd/xhb7d"
    "oB4uaYEWP7iD4QFlDC3an59fxLLNcxny8Ktc06mKIdnHmDj0ABMHf2BkXUVNJ3LnvWKVgKIE"
    "VICEjEWnn+9MD1BT156M5Gr1t56VEjSrTCw2yPPXtKtSHSK9F2gXfZlLV1IMfLV17eiUUBs6"
    "/2h6OifWhsmzjtq6dnROrlGdL2VpuoW3aNODfFnRg+fmFZGVeYbEOB9N/mi6zyoz3VCCNrrC"
    "eON9NPlUXuuh2nQDwnzTi47SCILqhBugfRz4m6C5AWJiNCb5HYXh1ZBDX5y/DJ/fzYlz3fno"
    "VF9+88Y9lJYPZ919xQAkxzfgfXo66R3Om/kV8+1A35jk+Aa8v55OervzZiskh6QmX6LyXCey"
    "MipCNHrZlXZfl2mNbL06AdAiEC3qun67sN5e0pIvUVWdRo9OVQZ+ocC579Ii6gGV91xVR65N"
    "P2daM3g1HbsOeSj9RSFdOtSoGHzwVWUXlUa6oVivsAbv8kK6pEq8Z1VeIQeFfIu0tBO3G2Kj"
    "gGgMn7sAirZHKecvQP1FaJFLoc/8rR9u9NIUI1rok3GKe4bt5tX5j7HzcL5RUof3PkLJ34er"
    "JUwqZXoJNsqipm947yOUlA83WkLYadkP+X3L2bJvglES5bKtz8W6ffiuuMMw6xuhZ6hhl9SC"
    "9E3QZY744Ufs+mCMcdLX5998f6zh+KDf4hvte1SfD3nj4FgDo7722oFxRkAJHzT5Y4kJ+k2+"
    "3uKdaGDUbWq64g61AplX+EMt1Adb9km8dodM2b/NECeAOC1g/OC6ISpUDwJ+uFgH/kbLJkpg"
    "9eeCZ55lx/s3cbaqI80NLqqqO/DH0jvJy/6HsYGLx7/I2rdmse3AeGrPJ3OlPpb9nw7irmdX"
    "GLJ05wR9Ifqt+1X6y/Wx7Pt0EHetW2HQPDJhI9sOTmDNznv5pjKdpitu/v5FH37y+6cMmT06"
    "VlL2cS7NTUrYmcLuWT57WINn8fiXeK7sDjb+ZTLVNe35rqY9G8tu53hFdxOd6TqqOX7x+BfZ"
    "8NepvFA2hW+r2/NtdXuef2cqpyq7mfTn9znMsi3zqKrpQHVNe9a/fSfffJdhBKdu07sf59LS"
    "qJjObjrvt9Uab4mF12KbNckSgYRELSj8QKNWhPTX3G/ODYgYN6QnQ1qi+qZLoP6xxPhrnlY+"
    "D50YwMb3p/LByYE0+uPIbFfNpP77mJ//CinxDUZF/byyJytLHqD89PUEAlHc0OMYC27azIjr"
    "joAC3R7xUrHGY5S4zysi0Gsl82xtOqvevo99x4dS15hE74yvmDf2FSYP9CIA7z+HsmznAr6u"
    "7UJQRFGx2gNA10e95uc1HuOmoEhlueujXs5qdABHK3ry1O5CPjydQ1y0j1sG7OOxiRsYWrSd"
    "U8+MM3cO/QaCKvNoZRZP755D+enriXP7mdR/P0UFvyd7yTucXe1BUeDClWSW7ZzPe//MJShc"
    "TLz+AE9N+S29fl5KxWoPAnjvX0NZ/qZk0xoVnx1vUcFv6f1kacg+LDccVIxJsZCcBqQBCeqa"
    "a7Tlbx8AZfMDAiA1ETokqAcQIUJGIgu3vnlzeLsZNsJOrxFo2yrL+qYzkjwnGuvbSjs6Td/+"
    "E4N5+u1C9i64P7KMtvjEzoa2Yr7aNaEme0IcpLQDOhJqHU3gKlCDwvSfVzf/LkopmxMQ9fVq"
    "8MTHQ1Bg3MHtrrr6sL7RludtXnXY+stuD2z2JEyunW4njDZX9YgxMvvVp3lo2Db6ZZykOeDm"
    "b18PYHnJPB4b+2eiWlr3RWs+s7PBCac8YcVvp1ueVIC4KEiJA1cSau8IAg2AD1wzHP50ro8P"
    "CgMiNQGSYyHODUkxEO1GPZYGJUL9RBIME2EeVj6Z18pvp8NOvqzb+myn6z+ke/2zkazdfyef"
    "VWURCLrIyTjN/BFvMHPQu5HxtQV/0IHGyTYn+Ug0LsLtc6FGSQxqtseglgMFNSDua+WfbPRx"
    "alFAuLXe014XZPvyAuf0jvQcibet5be1VtHWlmblseK6mmFXglorT5HsdtJxtet6UMRiBImr"
    "0P5/NR2DQh7+JwLCrQfF9+P/d0SrH9fjkf9x999mqyGfg0nrHQAAAABJRU5ErkJggg=="
    )

# ---------------------------------------------------------------------

generate_cluster = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAJgAAAAXCAYAAAD3JIYsAAAABHNCSVQICAgIfAhkiAAADh9J"
    "REFUaIHtm3t8VNW1x7+TBEMeJCEJkgAXtFRFHhqEGJ4SRB5KQUgtBIVAlVdQtIitRfDqBVps"
    "7dUKiAgIgRSqBVus6IUqJJELJkp5iCBSRcj7/c4k50xmzv3jPGafM2cm6f3c/tFe9ueTz8yc"
    "vfZav/Xba6+1956JwxEUzPV2vf2jWkhnhDxut/KPBnK9/XO2oOBgR6B+h78Mdj2orrfONMkJ"
    "Tc1QUwe3D/QNNtsAswaXqxUkFygeXwMK4NBe0d6jgKI9dDi8MuIYvc+fPut7u35/Y3QcBjar"
    "La3DTtZfs/VT042j85j86Q303J/PBnYbngPZNHRoQjo3HXFgbUFB6piGeigrA9kFY8aZg8wn"
    "wMTgamuC5hZob8fMLviwrQAOm5yn6A6IsormiI1OIxj8MaQIev3ZssiaMNrosm1WbJ3ps7Nt"
    "x5sNNr/yncFnGfP3Bopf3XZYLTYcQeCSob4eqmvVJDRhsjfITAEmBlddJbS0gEcxa9VXismw"
    "TXboTKox6RL69VXplyUtQBWHGtSKJqcHuDV7ijhFeVGPjz8W+9ZsolgnwGZMv/65XPs21eyf"
    "VaEVh47bXwDaPbP6ZdcUQU4Yb6gJwLWdnzpGnYf2dqirg8oKtdr9cLYaZMYmXwyuiiI1c6GY"
    "Occ6OQ5fzvRM5tfZztY9P81fLNhh6mwyEGUDLNqAsg6bVwBZssdm1Se4YNZhKecAtwzM5W8X"
    "U+0xCcatZd0qa1rQncUlVBh9jvXFEN5VLZulpbB9i1tZtCzY4XOKLL4CzU1eACaQwgqwMy6i"
    "95vI/KRzvbwZ5dOiS3S4s2QgEGCHxScQhVVtbQZOceU7hG2BkHXE8bJsCRRRRsxUgi5F4Nmk"
    "T+BOluyD2o53E06rfkufXfNZTAIOcXG7PdA1VC2TpaXqY1OAVReptdTtsmhEAAN8ffl7vLop"
    "k7PnBhMaKjNxQi4rn9rCyNQjnC1INRCdOn0Hr27M5PI3/YmPq2XRo3tIe/BDQ2fSiFz+enI8"
    "b+1+hD+99wOqqmPplVjBnFnvMmfWQVMknTpjo2v6hypZQFJKLvl5k3h181L+8nEqdXWxnNGw"
    "OBxQURnHzqxH+POHU+ge08DECblkLt5J11CXikUb/9tNSzly1DtezAgioQ6gtPRGtmx7lE8L"
    "kmlo7MbNNxWycP5eJk/MMca4tAyWlJLL2YJUY+GKe8WklFzO5qcC0OIMY9tbGRzLG0tlVTwh"
    "Ie0MHniJh2cfYNzYfJJScgEYNDTXGG9wjsb5Ji9Pix/dw8zpHxqgk1Jy+TRvEq8Jfuq2m51h"
    "bNuZQU6u2fYj6Qe4Z0y+b0q0rETFA6E3QFgoXKkTAszT5FZaqqCyCtqcwqqyKV3XivqwdPlv"
    "WLhgDy889wsAjuak8uL6ZwBvSbhW2IeVP1/LT5/ayKiR+Vy71pfVL/47iT1LGDb0nKFv3YYV"
    "xEQ3sPmVp4mPq+Grr29j7YZniYpsYOKEHJOuZ57ayGhd13/46lr/0k9IGX6KJT/eQWSk05hc"
    "BzB/4essWpDFf/1pG/UN0WzeuoQ33lzA44u3Gz6uf+knpCSfYvFjO4iM0Mb7SQ3l5TfyaObr"
    "pE1/nx1bHqdHfDWXLt9K9r45jB+XY2AySqTw3i4Ty7L6uvqFVSQmlLP5lafpEV9DizOcL74c"
    "xL530hh5dz6ffZLK3ffk8tknqWa9ijo3K1dpPI3I51qhylNCzxKGJZ0zDP/C6qesYlljZ/v8"
    "IPa+ncaI5Hx8mnXxKaC41cVTWwsvr3crIQCNDdDYDC1N6lHTWrLENLrtrfnM/uF+Zkw9aBA0"
    "4wcHaWiI9BKlwI6secydvY/xY48BcEv/SyzP3MzuvencMdAbFDFRdSycv8swOmTgF6x4YiO7"
    "suczbmwODqsuB9za/xLLl2q6Bp0zFsTN/a4w/p5jOAQc+oS++7t0g4/42DZWLn+Fx5a9yaIF"
    "2w2Obu53xcDrkgLvw7bu+DH3TzpMxsN7DOwDbrnIL1943ghsqx6xrOnN2KtpeAs+H857bz9E"
    "eIQTxQ1hoU2kDMsnZVi+Md6qS3/dkTWPeekWzjWehgicm/yUvQml4PPhHHz7ISIinHjcEB7a"
    "REpyPinD822xi03va3epOp1O9foiCEBqA6kFJEl1VJZVB2Tts0tS+yQJTp0exthROYaMS5NL"
    "HXPUcNwlw/kvBzNi2AkkGSRN56DbvuCbb79vjAWYOP6w154Mchvc1v8ChcV9kNvU5+e/HEzK"
    "8BMGJkmCgbquNm8ZGnn3cWTNnqvNi72pqQvbszKYs2AP46ceZszEXO5PO0R5ZYKqT8seo5KP"
    "m/wVfXRpfrm0Z/mfJzMp9bBtn+4vaFgkbxBJspcj3Y4eiLIM/fpe5bU3MikpiUMS9Qq6dXlJ"
    "8o6TNc7vvuuE95nAk44RYKTmp86ljrtf36tsfCOTktI4Fauk8qjPsW7H+Cxwo/MlSeByqX+y"
    "SyuRTie0aZPpcmG6eDNWmfahoTGaqIga0+lIcUC3iBojwFCgsroH85bs9Y10hxu5zfs5Nqbc"
    "uzq0vUnoDc00N0cZhFRW9yBjsR9dshdndGQ1rjZRQH3Z+tZiikr68fMVa+nTq4iuXSVkuQvT"
    "0j8yreCobtVqxhFOV3qz7hbqG2KIjqoyJlzfq1nlxAzmEjjThTwe9Y3Upvq+asVa3tz1OHMX"
    "7SPhxnIG3HqRUSnHGZl80rRvkyTzPs7gyR/nkvfUF635qWPR97GrVqxl667HmbvQ17bdVYh4"
    "GtVPyHqwtrer79USWQ/OVm+HlVSRtKhuDZRXxJHQs9yULysq4kwkhoc52fSrdGK711rQeFc3"
    "QLvLJulqxmRJfR8W5mTzr9KJja31AsMsA+Bxu5Hdvuo+OZnKf67LJD6uGhzqmMLiXt7xWMZb"
    "TrM2W1GiujVQVtaDXr1KfDCJPkja4okIb6K2NoLIiBaTWFlFAuDNLrEx5axa8TwuVwjFpX35"
    "+puB7PvDPE7kj+apJS8b41wyPi08zMmmX6cTGyNwrvMkyPvjKTamnOdWPI/cHkJJiY3tADVS"
    "f9zSou6/nE71LwigokI9PcpCmpMlaBfSoP465Pa/kvff443ypf8dOz7BcESWYPCAM5zMH22S"
    "Ef90guxKsj7psqSWzMEDznAif7TXpmz508uM8FksE5IUCors7ZPhyLH7vTZELJrNdqHktVts"
    "uiQYOuQzjuRMMXEj6rdiSkwo4sLFQabSIstw+OMHTDj0fjzt9E64wr1jDrHm6Z9x/OS9Rn+X"
    "LhJOZ4iZOxkGDTjDiU9Hm/wwvYq8ymbMJi7d7fROvMK9Yw+x2mLbOl+i/61OqK6Bq4XQ0ADN"
    "zVqATfpRsKO5Waudwp5Cks17AEmGmVN38/7hH/HBX6ZTVR1DVXUMh448SGFRX5VQbfyMB7J4"
    "5735fJQ7mZrabjQ2hnL63FDW/WaDUft1eet+Ty9zsmZ75tQs/qDpqq3uRlNDKKfPDGXdyxt8"
    "iWvTsOvEynDn4AJ2ZD9BZUV3qqpiePfPs6jQMoe+79PH66SL400LQ+tPm7qLnE+msO9ABiUl"
    "PWlpCeHiV7ez4bfrDDlR5/337md79pN8cWEITU2hFBYnsuf3i6hviDYC0SXBc+tf42jefZSW"
    "x9PaGkRlVXf++MEsBtx6zpiXnvGlFJxKQWp1mHDNfEDjKUfjvCmU02dVzvU5NHi1BpcEq9e9"
    "xrG8+yiriKe1JYjKyu4cFG1L5vgwFrQMbRI0NkJxMRQVq5Vw77vCRWt9nZoBg0O8mdXnS1AH"
    "xMcUs3LZT3n7YCbZ+5dxQxeJ5KQ85sx4nYLTqUatT4i/xsqlz7L//UVk/f5J3J5gvn/TRaZP"
    "zjala72EiKlW/6zvX3rG2euaNiXbdGITy53Y5qZtJPvAcp55MQtFCWLYHcd57OGXKDidaj7x"
    "aSc5P9c8phIRHVnJmhVPcODQY6z+5Vaczkh6J15l2qS9Jhy6/uQ7c6ivj2Zr1s+orkkgOqqW"
    "caM+IOOhHRw7Pl3dyymQ9sBOPspLY887y5HkrnSPqSI5KY+lGWtVboH0GVvIPvAkr25di6IE"
    "s3tTKg78cz5tcraJZwOf5dJ4pmZ7t8V2ZsZada8rlEeRG48Cra1QXA4XLkFtHcREaXL6d5G/"
    "XuNWZFm9iY0MB/0rSp8vnoVNoViPL1wexv73M3lx5ULfyzjrVbBds86m3Vne7hk2N+hWeTs8"
    "VmziTbcNJJPPdpeNwoV0oMD066d+QPB3ianvCe1WY2f9FPFYMFhv+32aZV+q6/QoavYqK4fz"
    "l+C7IghywJeX1e8iTV92r3nSrSgeiAiH8HAIDgJHkAWTAlt/t577xrxD78RvcbtD+Nt3d3Lg"
    "gyeYNnEnI+464h+kcNrw67BdMNqdXGx063I+34XaznqAfsvpRg8sxQ5AR3qtMiJOBC5s9JhM"
    "6YtIuJu0HacI4+zICrT4rP3+FpI2hx43tMlQXgkXL8PVYrX/pn+Dw3k2AQbw7BK34nLDDSEQ"
    "1hVCQyEk2Izh/FdjySuYRVnl9/B4gki48TvGJv+Ru4Z87J+gv6N1ZsFbhf8vbAV61qGsfowH"
    "03eq+mdr6bVJnH7tdEbOLt46k8zsdFrHi8/1BeFqV38QUVULVwqhuEz1uV9v+OiEn5/r6G3Z"
    "XLfS2KRmsK5hWoDpPzYMhLAzq8PfitLHWdn3V2I70h1oVkRbom07HwI1f6U7UOnqSJ9d5AXI"
    "6MbzjvztCGdHNsXnHmhuhcpqqKqBxha1LPZJhKOfdvCDQ71lPOhWGlvUC1hnm/obn/9Virje"
    "/uWaoqi39M5WdQ8WGQ5nL9n/Nt9vgIlt9hS30mY5RVxv/3+boqjXELILjhYE/qeP/wFEtsfz"
    "5UjFOAAAAABJRU5ErkJggg=="
    )
