#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
# ##############################################################
#                                                            ###
# Universidad Nacional de Asunción - Facultad Politécnica    ###
# Ingenieria en Informática - Proyecto Final de Grado        ###
#                                                            ###
# Autores:                                                   ###
#           - Arsenio Ferreira (arse.ferreira@gmail.com)      ###
#           - Abrahan Fretes (abrahan.fretes@gmail.com)      ###
#                                                            ###
# Creado:  1/9/2016                                          ###
#                                                            ###
# ##############################################################
'''

# ---------------------------------------------------------------------

# This file was generated by image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

# ---------------------------------------------------------------------

# ----------------------------------------------------------------------
smiles = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAolJ"
    "REFUOI1tk91Lk2EYxn/vx7OmwyBhVsytmY1cCBFBQWSRlYVGJ51EjajptliH4X/QQeJ5J+ZJ"
    "f0AnIVSWJ0EQQfQhzNG3JkRQILrl3tft6sDNRvnAdfI8z8V939d13Vi2w79IpS4pHt8p17Vk"
    "jK1EIqpcLqPN/to0nWwmrc5IUL29n3jw4Ajl8mVKpYvcv7+frq5HdEZqymauqZljWbYDwOlT"
    "xxSL/eTOnfMY4wElYAWoAhXgI75fIJ/3mJ8/wvST5xaw3kE2k1YsBhMTtzEmCYTqxEaxVaCM"
    "MRYTE1uIxZ6RzVxdf7Rsh2i0XZ5XkPRF0mONjo4KkJSSlBKgcDgsqVVSizwPRTuRZTu42Uxa"
    "XV1rGNMCOECN8fHxpimX6OnpYW5uDmgF1TAEuXG9yuf5lOyZmYcMDUWAReAj8LqJXAEWWVhY"
    "aLqrQaWVoZNtzMxMYRljq1S6iTFtwCrDw9+ZnPQ2hIOFuqB1crUKSx34qw6hXfMNG7264stM"
    "TvrAEvAOKDaRBVpjd2cQ/BbwgwDY8XiEYvEb8AMokky+BF7UK+svGR+qNp+/L0O5jeKcRXxX"
    "GLe//wxTU/fo7Q0AolCAUEiUGoWpAWtQtTi4rw19iUB5K1OPf9F//GTDRkue11K3ad0qBYMK"
    "BAJyXUehoKv93e3S4l6p0Cfv1QlFdwS0EeXBwTT5/Op6mw389qn4Pr5jcTjZweunUVgOw1qA"
    "/K0ig2fOsREky3YYGOjTyAjyPCTVUbWllW3St6T04ZC8N0c1cmGHBo4f0H/LNP3kueU4w3R3"
    "w9gYzM6CX3HwKzaz71cYu/uV7rMvcLb2Mf3srbURi81WNJdLK5HYLuMi46LEng7lMlc2Xec/"
    "xiMt8QU2mDwAAAAASUVORK5CYII=")

# ----------------------------------------------------------------------
small_up_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUOI1jZGRiZqAEMFGke2gY8P/f3/9kGwDTjM8QnAaga8JlCG3CAJdt2MQxDCAUaOjyjKMp"
    "cRAYAABS2CPsss3BWQAAAABJRU5ErkJggg==")

# ----------------------------------------------------------------------
small_dn_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEhJ"
    "REFUOI1jZGRiZqAEMFGke9QABgYGBgYWdIH///7+J6SJkYmZEacLkCUJacZqAD5DsInTLhDR"
    "bcPlKrwugGnCFy6Mo3mBAQChDgRlP4RC7wAAAABJRU5ErkJggg==")

run_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAPhJ"
    "REFUOI1jYBgFjNgEsxebf/315xfXr39/uBYmX/6OzwAmbII//vxikBHRZPjx+/c3/6nynCQb"
    "wMPGw6UpYc4gK6zO8O3Xjy+23YI8JBnw598vhmcfHzPoylgzKIvpM/348+2jbjMjP0le+Pb3"
    "O8PDd3cZDGRtGdQlTZl+/Pn/lgQDfjD8//ufQZRXmuHc46MMR+8eef3tF4MJNrUs2AS//fnB"
    "IMgtxnD64RGGvbd2vfj1h8H5eTvDNWxqmbEKWnws+/+fmXX/zT1Pf/1lcHreznADmzoGBhzp"
    "QLGW4evff8xc3//9VXrdznAfl2a8QLicAW/8Dx4AAHR1YeN2C0QUAAAAAElFTkSuQmCC")

refresh_plot = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALNJ"
    "REFUOI2lk7ENwyAQRR/EUopUtBRRRrHEAh7E43gQFkDyKFEKt65SkyZEGLBNxK/Qcf/r7t+d"
    "8N57GiBbyABdGtBjnyUt01wnoMceMygAnF0zYhCP4zL+PCObQWEGtamyyoNYHNiInAqERGfX"
    "Xyy89djnJqYIraTmhnhXcj0mHE0AQIaEtMcaMnw9WKYZZ1eu8gKUp7AHEa/yXtlHIxalW3i9"
    "n9xvj6qtLAr8g+Zjahb4AEW6VPXp5dKQAAAAAElFTkSuQmCC")

# ---------------------------------------------------------------------

change_normalization = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtlJ"
    "REFUOI2l011sTGkYB/D/OfPRj6O0THVMfU5bSTWpcGy0vhMyNljJSnAhrgQJLsTFJnvBnbjD"
    "BRd1sSEp2WR9hERtNruEIrpyhLFV206nVUa100Or8/E+z3vmvC7oNNSNeG7/ye/JP08eTcP3"
    "jRcAVv820ATA/EpuATgGwAcgpZSy7+wK8gQgl8u1QilzeyRkEqmPgUfDxZuv8fOaGXPsES5P"
    "DAnue5NNrTiT6Li7p7J/DNAB4O7uULPjOH+eb+mzNOUiPSpBlIPjOJDsaobPU1ETLJ6zsbG8"
    "zu9VkYbTveHPAPNEZwg5uXzT0unm0GAGhQWAFBKSGX/83TPa1j5QkspS9bAtqiJLAos05LaZ"
    "JzpL84DDvGVusLB65F0GXq/ChZYuy+cHHCJYB2usvsTIXzdaX2QFc9geTFfPDhTUO8wr8wAT"
    "LZ9meKcySfzbPtDNRA/OXnlmMREA4PEvdY8k851obKiISYYDJd5aJlqdB6QQNR4dxY5y0d2T"
    "HO44Yh5wiE46RNZY12eHF7fEe5J+R7mVHh1hKcQP+SswUTrrqPfSUWCiNAB0HV3WDKB51qF/"
    "mgC0vjy+tpmJjLSjJvugwETGeAUhHiZHKW4LN1EeMDi47/qGsc2SyJREB4P7W06VB4xSW7hI"
    "pijDQnSNVyC63fdqqMOGL142rzIrmVdN3XV58acMa7csMyVRQ2BBVZUNH14m7LeS6N44wNza"
    "+/+LaGGpEUt4jHh4XUNRSUVZpGTn7yYToTujY+HWdWYsq8M1ihFr741J5ssA4NEA0JOLQpv/"
    "0+uBzl5/xZK6TL8qeIuZs6isvnZk+FE0UrSoPhRPa5hR6sfTc5esnJS30hd2XM0DACD/u/LO"
    "nffjYDL6XPlYZPWiAqGmTE4Pt1nryxrNkPJ6kFI65jbWh/rvW4ZeuznjPr8W1b78Rn1zk18p"
    "NQ3AJE3TJIBflVITHk3TNMu9tnfvBOBb5wOI/oIVnOBIyAAAAABJRU5ErkJggg=="
    )
